### ISSUE TITLE
Do you have instructions on making new patterns for a custom game?

### ISSUE THREAD

**Issue by ArdisFoxx** [MinLL/GameInterfaceForToys#34]
I've successfully got a custom game working but the vibe pattern isn't very interesting. How do I add more variance to it? Right now I am just using triggers like the below.

- Player Character Damaged:
    regex: .+{GIFT_ACTOR_NAME}, Damage+
    function: generic_random_vibrate
    toy_class: vibrator
    params:
        min_duration: 1
        max_duration: 2
        min_strength: 25
        max_strength: 45

I see in the Skyrim related folders there are some options with numbers like 10, 15, 20, 15, 20, 5. I presume this is a kind of strength pattern or something? How do I configure that for a custom game?

**Comment by AnonWhoKnowsNoAnons** [comment]
As far as I understand you just create patterns in this file
pattern_dict.json
(open with notepad or notepad++)
Then the function: Your_New_Pattern_you_just_created_and_named_this

<img width="886" height="335" alt="Image" src="https://github.com/user-attachments/assets/bec52485-0360-4360-aea6-f93da14f9e8d" />

**Comment by AnonWhoKnowsNoAnons** [comment]
I should come back and note I don't know if the link is the "function:" directly to the patterns.
Patterns definitely in that patterns file, but function seems to link to other files first. In the process of trying to figure out it myself.

**Comment by AnonWhoKnowsNoAnons** [comment]
Figured it out, took ages, with all the quirks.

```
In your .yaml file for your mod
- name_of_your_mod_event:
    regex: '\[.*?\] .*The exact line of text that you want it to read in the logs from your mod'
    function: generic_random_vibrate
    group: 0
    toy_class: vibrator
    params:
      duration: 300
      strength: 100    
      pattern: "The_Pattern_You_refer_to"


Then in patterns_dict
    "The_Pattern_You_refer_to": [[8, 16, 8, 16, 12, 16, 8, 16]],


Also need a reference to the yaml file in events.yaml

```

Also need a reference to the yaml file in events.yaml

Important things, make sure the different brackets and symbols are exact, don't miss some. e.g. I missed the 2 brackets on each side of the pattern, which then caused my lovense devices to not be able to read the whole line since they're looking for a list of multiple series numbers within brackets of other brackets.
The regex I just figured out one structure that works, don't know why it couldn't be simpler.

Extras
if you want you can add more variations into the params, with min and max, and strength difference. Look into log_reader.py to figure it out

I used chatgpt to figure this out, so if stuck can use that, but be careful, use your brain though, it fails a lot but is helpful.

EDIT: realised you want it for a different game, so you would just need the game to give a log file that you point to in settings
